config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }

  root 'foods#index'

  resources :foods, only: %i[index show]

  namespace :admins do
    root 'foods#index'
    resources :foods
    resources :orders, only: %i[index show]
    resources :users, only: %i[index show edit update destroy]
  end

  namespace :users do
    resource :cart, only: %i[show] do
      resources :cart_items, only: %i[new create edit update destroy], module: :carts
    end
    resources :orders, only: %i[index show new create]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/headers/_admin_header.html.haml
.navbar.bg-light
  .container-fluid
    .d-flex.align-items-center
      .navbar-brand.fs-2= link_to 'Sakura Market for Admin', admins_root_path, class: 'text-decoration-none text-dark'
    - if admin_signed_in?
      %ul.navbar-nav.flex-row.gap-3
        %li.nav-item
          = link_to t('admins.navigation.users'), admins_users_path, class: 'nav-link'
        %li.nav-item
          = link_to t('admins.navigation.orders'), admins_orders_path, class: 'nav-link'
    %ul.navbar-nav.ms-auto
      - if admin_signed_in?
        = button_to t('general.logout'), destroy_admin_session_path, method: :delete, data: { turbo_confirm: t('views.log_out_confirm') } ,class: 'btn btn-outline-danger'

app/views/layouts/headers/_user_header.html.haml
.navbar.bg-success-subtle
  .container-fluid
    .d-flex.align-items-center
      .navbar-brand.fs-2= link_to 'Sakura Market', root_path, class: 'text-decoration-none text-dark'
    - if user_signed_in?
      %ul.navbar-nav.flex-row.gap-3
        %li.nav-item
          = link_to t('users.navigation.orders'), users_orders_path, class: 'nav-link'
        %li.nav-item
          = link_to t('users.navigation.cart'), users_cart_path, class: 'nav-link'
    %ul.navbar-nav.ms-auto
      - if user_signed_in?
        %li.nav-item.d-flex.align-items-center
          .me-3= link_to current_user.name, edit_user_registration_path
          = button_to t('general.logout'), destroy_user_session_path, method: :delete, data: { turbo_confirm: t('views.log_out_confirm') }, class: 'btn btn-outline-danger'
      - else
        = link_to t('general.login'), new_user_session_path, class: 'btn btn-primary'