config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }

  root 'foods#index'

  resources :foods, only: %i[index show]

  namespace :admins do
    root 'foods#index'
    resources :foods
    resources :orders, only: %i[index show]
    resources :users, only: %i[index show edit update destroy]
  end

  namespace :users do
    resource :cart, only: %i[show] do
      resources :cart_items, only: %i[new create edit update destroy], module: :carts
    end
    resources :orders, only: %i[index show new create]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  validates :user_id, uniqueness: true

  def total_price
    cart_items.sum(&:total_price)
  end

  def total_price_with_tax
    cart_items.sum(&:total_price_with_tax)
  end

  def total_tax_amount
    total_price_with_tax - total_price
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :food

  validates :food_id, uniqueness: { scope: :cart_id }
  validates :quantity, numericality: { greater_than: 0 }
  validate :validate_food_is_published

  scope :default_order, -> { order(id: :desc) }

  def total_price
    quantity * food.price
  end

  def total_price_with_tax
    quantity * food.price_with_tax
  end

  private

  def validate_food_is_published
    unless food.published?
      errors.add(:cart_item, :validate_food_is_published)
    end
  end
end

app/controllers/users/carts/cart_items_controller.rb
class Users::Carts::CartItemsController < Users::ApplicationController
  before_action :set_cart_item, only: %i[edit update destroy]
  before_action :set_food, only: %i[new]

  def new
    @cart_item = current_cart.cart_items.build(food: @food)
  end

  def create
    @cart_item = current_cart.cart_items.build(cart_item_params)

    if @cart_item.save
      redirect_to users_cart_path, notice: t('controllers.cart_items.created')
    else
      @food = @cart_item.food
      render :new, status: :unprocessable_content
    end
  end

  def edit
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to users_cart_path, notice: t('controllers.updated')
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @cart_item.destroy!
    redirect_to users_cart_path, notice: t('controllers.destroyed'), status: :see_other
  end

  private

  def set_cart_item
    @cart_item = current_cart.cart_items.find(params.expect(:id))
  end

  def set_food
    @food = Food.published.find(params.expect(:food_id))
  end

  def cart_item_params
    params.expect(cart_item: %i[food_id quantity])
  end
end

app/controllers/users/carts_controller.rb
class Users::CartsController < Users::ApplicationController
  def show
    @cart_items = current_cart.cart_items.includes(food: :cover_image_attachment).default_order
  end
end

app/views/users/carts/cart_items/edit.html.haml
.row
  .col-6.mx-auto
    .card.p-4
      .row.mb-4
        .col-4
          = food_cover_tag(@cart_item.food, :medium)
        .col-8
          .fs-5= @cart_item.food.name
          %p= @cart_item.food.description
          %p.fw-bold= number_to_currency(@cart_item.food.price_with_tax)

      = simple_form_for @cart_item, url: users_cart_cart_item_path(@cart_item), method: :patch do |f|
        = f.input :food_id, as: :hidden
        = f.input :quantity
        = f.button :submit, class: 'btn-primary'

    .mt-5= link_to t('general.back'), users_cart_path

app/views/users/carts/cart_items/new.html.haml
.row
  .col-6.mx-auto
    .card.p-4
      .row.mb-4
        .col-4
          = food_cover_tag(@food, :medium)
        .col-8
          .fs-5= @food.name
          %p= @food.description
          %p.fw-bold= number_to_currency(@food.price_with_tax)

      = simple_form_for @cart_item, url: users_cart_cart_items_path do |f|
        = f.input :food_id, as: :hidden, input_html: { value: @food.id }
        = f.input :quantity
        = f.submit t('cart.add'), class: 'btn btn-primary'

    .mt-5= link_to t('general.back'), food_path(@food)